apiVersion: v2
name: observability-demo
description: A Helm chart installing the OpenShift Observability Demo
version: 0.1.0

dependencies:
  - name: minio
    version: "5.1.0"
    repository: "https://charts.min.io/"