jobKeycloakCertServiceAccount: job-keycloak-cert-generator-sa
jobBuildImagesServiceAccount: build-image-sa
jobSyncUsersServiceAccount: obs-sync-users

operatorCheckList: "rhbk-operator cluster-observability-operator grafana-operator opentelemetry-product"

# Cluster Observability Operator configuration
observabilityOperator:
  name: cluster-observability-operator
  namespace: openshift-operators
  channel: stable
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: cluster-observability-operator.v1.3.0

