apiVersion: route.openshift.io/v1
kind: Route
metadata:
  {{- if .Values.annotations }}
  annotations: {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
  name: minio-console
  namespace: {{ .Release.Namespace }}  
spec:
  port:
    targetPort: 9001
  tls:
    termination: edge
  to:
    kind: Service
    name: minio-console
    weight: 100
  wildcardPolicy: None