# List of cluster-wide namespaces to create for operators.
operatorNamespaces:
  - openshift-logging
  - openshift-loki-operator
  - openshift-tempo-operator
  - openshift-opentelemetry-operator

# Cluster Observability Operator configuration
observabilityOperator:
  name: cluster-observability-operator
  namespace: openshift-operators
  channel: stable
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: cluster-observability-operator.v1.2.2