annotations-wave-0: 
  argocd.argoproj.io/sync-wave: "0"
annotations-wave-1: 
  argocd.argoproj.io/sync-wave: "1"
annotations-wave-2: 
  argocd.argoproj.io/sync-wave: "2"
annotations-wave-3: 
  argocd.argoproj.io/sync-wave: "3"
annotations-wave-4: 
  argocd.argoproj.io/sync-wave: "4"

minio: 
  additionalAnnotations: 
    argocd.argoproj.io/sync-wave: "1"

  service: 
    annotations:
      argocd.argoproj.io/sync-wave: "1"

  consoleService:
    annotations:
      argocd.argoproj.io/sync-wave: "1"

  postJob:
    annotations:
      argocd.argoproj.io/sync-wave: "1"
      argocd.argoproj.io//hook: PostSync
  
  persistence: 
    annotations: 
      argocd.argoproj.io/sync-wave: "1"