{{- range .Values.operatorNamespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
    observability-demo-framework: "operators"
  {{- if $.Values.annotations-wave-0 }}
  annotations: {{- toYaml $.Values.annotations-wave-0 | nindent 4 }}
  {{- end }}
---
{{- end }}