{{- $allServiceAccounts := .Values.otherServiceAccounts | default list -}}

{{- if .Values.jobKeycloakCertServiceAccount -}}
  {{- $allServiceAccounts = append $allServiceAccounts .Values.jobKeycloakCertServiceAccount -}}
{{- end -}}

{{- if .Values.jobBuildImagesServiceAccount -}}
  {{- $allServiceAccounts = append $allServiceAccounts .Values.jobBuildImagesServiceAccount -}}
{{- end -}}

{{- if .Values.jobSyncUsersServiceAccount -}}
  {{- $allServiceAccounts = append $allServiceAccounts .Values.jobSyncUsersServiceAccount -}}
{{- end -}}


{{- range $saName := $allServiceAccounts }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $saName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
  {{- if $.Values.annotationsWave0 }}
  annotations: {{- toYaml $.Values.annotationsWave0 | nindent 4 }}
  {{- end }}
---
{{- end }}

