{{- range .Values.operatorNamespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
    observability-demo-framework: "operators"  
---
{{- end }}