{{- range .Values.operatorNamespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
    observability-demo-framework: "operators"
  annotatios: 
    argocd.argoproj.io/sync-wave: "0"
---
{{- end }}