apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.observabilityOperator.name }}
  namespace: {{ .Values.observabilityOperator.namespace }}
  labels:
    operators.coreos.com/cluster-observability-operator.openshift-operators: ""
    observability-demo-framework: 'operator'
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: {{ .Values.observabilityOperator.channel }}
  installPlanApproval: Automatic
  name: {{ .Values.observabilityOperator.name }}
  source: {{ .Values.observabilityOperator.source }}
  sourceNamespace: {{ .Values.observabilityOperator.sourceNamespace }}
  startingCSV: {{ .Values.observabilityOperator.startingCSV }}