apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.observabilityOperator.name }}
  namespace: {{ .Values.observabilityOperator.namespace }}
  labels:
    operators.coreos.com/cluster-observability-operator.openshift-operators: ""
    observability-demo-framework: 'operator'
  annotations:
    # --- ARGO CD SYNC WAVE ---
    # This (Wave -1) runs FIRST and must be healthy
    # before Argo CD moves on to Wave 0 (the default).
    # This replaces your "wait_operator_to_be_installed" logic.
    argocd.argoproj.io/sync-wave: "-1"
spec:
  channel: {{ .Values.observabilityOperator.channel }}
  installPlanApproval: Automatic
  name: {{ .Values.observabilityOperator.name }}
  source: {{ .Values.observabilityOperator.source }}
  sourceNamespace: {{ .Values.observabilityOperator.sourceNamespace }}
  startingCSV: {{ .Values.observabilityOperator.startingCSV }}