apiVersion: v2
name: obs-minio
description: Parametrization of MinIO for the OpenShift Observability Demo
version: 0.1.0

dependencies:
  - name: minio
    # The version you want to pin
    version: "5.1.0" 
    # The Helm repository where the Minio chart lives
    repository: "https://charts.min.io/"

jobs:
  installPlanApproverServiceAccount: jobInstallApproverServiceAccount