apiVersion: v2
name: obs-minio
description: A Helm chart installing the OpenShift Observability Demo wave 1 (Minio, Loki, Otel, Keycloak, Grafana and Tempo Operators)
version: 0.1.0

dependencies:
  - name: minio
    # The version you want to pin
    version: "5.1.0" 
    # The Helm repository where the Minio chart lives
    repository: "https://charts.min.io/"