---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bootstrap-scripts
  {{- if .Values.annotationsWave0 }}
  annotations: {{- toYaml .Values.annotationsWave0 | nindent 4 }}
  {{- end }}
data:
  start-build.sh: |-
    {{- .Files.Get "files/start-build.sh" | nindent 4 }}
  minio-create-buckets.sh: |-
    {{- .Files.Get "files/minio-create-buckets.sh" | nindent 4 }}
  wait-for-operators.sh: |
    {{- .Files.Get "files/wait-for-operators.sh" | nindent 4 }}
  extract-tls-client-lokistack.sh: |
    {{- .Files.Get "files/extract-tls-client-lokistack.sh" | nindent 4 }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: sync-users-playbook
  namespace: {{ .Release.Namespace }}
  {{- if .Values.annotationsWave0 }}
  annotations: {{- toYaml .Values.annotationsWave0 | nindent 4 }}
  {{- end }}
data:
  playbook-sync-users.yml: |-
    {{- .Files.Get "files/playbook-sync-users.yaml" | nindent 4 }}