apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-waiter-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    #argocd.argoproj.io/sync-wave: "2"
    #helm.sh/hook: post-install,post-upgrade
    #helm.sh/hook-delete-policy: hook-succeeded
    #helm.sh/hook-weight: "4" # Runs before the job
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-csv-reader-role
rules:
- apiGroups: ["operators.coreos.com"]
  resources: ["subscriptions", "clusterserviceversions"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-waiter-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: operator-csv-reader-role
subjects:
- kind: ServiceAccount
  name: operator-waiter-sa
  namespace: {{ .Release.Namespace }}