apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-waiter-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    #argocd.argoproj.io/sync-wave: "2"
    #helm.sh/hook: post-install,post-upgrade
    #helm.sh/hook-delete-policy: hook-succeeded
    #helm.sh/hook-weight: "4" # Runs before the job
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-csv-reader-role
rules:
- apiGroups: ["operators.coreos.com"]
  resources: ["subscriptions", "clusterserviceversions"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-waiter-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: operator-csv-reader-role
subjects:
- kind: ServiceAccount
  name: operator-waiter-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: operator-waiter-job
  namespace: {{ .Release.Namespace }}
  annotations:
    #argocd.argoproj.io/sync-wave: "2"
    #argocd.argoproj.io/hook-delete-policy: HookSucceeded
    #helm.sh/hook: post-install,post-upgrade
    #helm.sh/hook-delete-policy: hook-succeeded
    #helm.sh/hook-weight: "5" # Runs *after* the RBAC/ConfigMap
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 600
  template:
    spec:
      serviceAccountName: operator-waiter-sa
      restartPolicy: OnFailure
      containers:
      - name: waiter
        image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
        command: ["/bin/bash", "/scripts/waiter.sh"]
        env:
        - name: OPERATOR_LIST
          value: {{ .Values.operatorCheckList | quote }}
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
      volumes:
      - name: script-volume
        configMap:
          name: bootstrap-scripts
          defaultMode: 0555
          items:
          - key: wait-for-operators.sh
            path: waiter.sh