apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: traces
  namespace: {{ .Release.Namespace }}
  labels:
    observability-demo-framework: traces
  {{- if .Values.annotationsWave2 }}
  annotations: {{- toYaml .Values.annotationsWave2 | nindent 4 }}
  {{- end }}
spec:
  tenants:
    authentication:
      - tenantId: obsdemo
        tenantName: obsdemo
    mode: openshift
  managementState: Managed
  serviceAccount: traces
  template:
    gateway:
      enabled: true
      ingress:
        route:
          termination: reencrypt
        type: route
    queryFrontend:
      component:
        replicas: 1
      jaegerQuery:        
        enabled: true        
        monitorTab:
          enabled: true
          prometheusEndpoint: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
  observability:
    tracing:
      jaeger_agent_endpoint: 'localhost:6831'
  search:
    defaultResultLimit: 20  
  storage:
    secret:
      name: tempostack-minio
      type: s3